### ISSUE TITLE
Use `MinidumpContext::get_instruction_pointer`

### ISSUE THREAD

**Issue by luser** [heycam/chkimg#2]
You've got code that does this:
https://github.com/heycam/chkimg/blob/752c24e1ecd0cde681c115c1ff91ddff6067e16e/src/main.rs#L294

but `MinidumpContext` has a helper method for this purpose:
https://docs.rs/minidump/0.1.0/minidump/struct.MinidumpContext.html#method.get_instruction_pointer

**Comment by heycam** [comment]
Oh indeed, thanks!
